development:
  adapter: redis

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:f0c9b6534ab0d87d781eecf45c505047@grouper.redistogo.com:9353/
  channel_prefix: netidej_production
